---
platform: linux

inputs:
  - name: fluentd-boshrelease
  - name: version

outputs:
  - name: final-release

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: fluentd-boshrelease/ci/tasks/create-final.sh
