---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
  - name: fluentd-boshrelease

outputs:
  - name: release

run:
  path: fluentd-boshrelease/ci/tasks/create-candidate.sh
