---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
  - name: fluentd-boshrelease
  - name: final-release
  - name: version

outputs:
  - name: bumped-version
  - name: final-fluentd-boshrelease

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: fluentd-boshrelease/ci/tasks/finalize-release.sh
