---
platform: linux

inputs:
- name: fluentd-boshrelease

outputs:
- name: fluentd-boshrelease

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  dir: fluentd-boshrelease
  path: ci/tasks/package-fluentd.sh
