---
platform: linux

inputs:
- name: fluentd-boshrelease

outputs:
- name: fluentd-boshrelease

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  dir: fluentd-boshrelease
  path: fluentd-boshrelease/ci/tasks/update-fluentd.sh
